/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bubbles;

/**
 *
 * @author Admin
 */
public class Analysis extends javax.swing.JFrame {

    /**
     * Creates new form Analysis
     */
    public Analysis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lrbc = new javax.swing.JTextField();
        lwbc = new javax.swing.JTextField();
        lplatelets = new javax.swing.JTextField();
        lsugar = new javax.swing.JTextField();
        lchol = new javax.swing.JTextField();
        crbc = new javax.swing.JTextField();
        cwbc = new javax.swing.JTextField();
        cplatelets = new javax.swing.JTextField();
        csugar = new javax.swing.JTextField();
        cchol = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaa = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 36)); // NOI18N
        jLabel1.setText("Bubbles HealthCare");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 20, 350, 35);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel2.setText("Please Enter the following details using your Lab Reports.\n");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 66, 660, 33);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel3.setText("Current Report");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(500, 90, 200, 40);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel4.setText("Last report");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 90, 180, 40);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel5.setText("RBC");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 120, 140, 40);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel6.setText("WBC");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 150, 150, 40);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel7.setText("Platelets");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 180, 170, 40);

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel8.setText("Cholestrol");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 210, 180, 40);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel9.setText("Sugar");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 250, 150, 30);

        lrbc.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        getContentPane().add(lrbc);
        lrbc.setBounds(500, 130, 200, 31);

        lwbc.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        getContentPane().add(lwbc);
        lwbc.setBounds(500, 160, 200, 30);

        lplatelets.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        getContentPane().add(lplatelets);
        lplatelets.setBounds(500, 180, 200, 40);

        lsugar.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        getContentPane().add(lsugar);
        lsugar.setBounds(500, 250, 200, 30);

        lchol.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        getContentPane().add(lchol);
        lchol.setBounds(500, 210, 200, 40);

        crbc.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        getContentPane().add(crbc);
        crbc.setBounds(310, 130, 180, 30);

        cwbc.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        getContentPane().add(cwbc);
        cwbc.setBounds(310, 160, 180, 30);

        cplatelets.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        getContentPane().add(cplatelets);
        cplatelets.setBounds(310, 220, 180, 30);

        csugar.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        getContentPane().add(csugar);
        csugar.setBounds(310, 190, 180, 30);

        cchol.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        cchol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccholActionPerformed(evt);
            }
        });
        getContentPane().add(cchol);
        cchol.setBounds(310, 250, 180, 30);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jButton1.setText("Get Results!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 300, 150, 30);

        areaa.setColumns(20);
        areaa.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        areaa.setRows(5);
        jScrollPane1.setViewportView(areaa);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 340, 716, 244);

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\data-2.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 790, 590);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 100, 630, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       		
                float sug1= Integer.parseInt(lsugar.getText());
                 float sug2= Integer.parseInt(csugar.getText());	
                 
		float chol1= Integer.parseInt(lchol.getText());
                 float chol2= Integer.parseInt(cchol.getText());			
		
                 float wbc1= Integer.parseInt(lwbc.getText());
                 float wbc2= Integer.parseInt(cwbc.getText());			 
		 float rbc1= Integer.parseInt(lrbc.getText());
                 float rbc2= Integer.parseInt(crbc.getText());
                 float plat1= Integer.parseInt(lplatelets.getText());
                 float plat2= Integer.parseInt(cplatelets.getText());
		
	
		float dsug,dchol;
		float dwbc,drbc,dplatelets;
		dsug=sug2-sug1;
		dchol=chol2-chol1;
		dwbc=wbc2-wbc1;
		drbc=rbc2-rbc1;
		dplatelets=plat2-plat1;
                float orbc,owbc,osugar,oplat,ochol;
                orbc=5.4f-rbc1;
                owbc=7550-wbc1;
                osugar=100-sug1;
                ochol=200-chol1;
                oplat=300000-plat1;
                
		if(dsug>0)
		{
			areaa.setText(areaa.getText()+"\nSugar level has decreased by "+Math.abs(dsug)+"mg/dl");
                        if(osugar>0)
                        {
                          areaa.setText(areaa.getText()+" and it is "+Math.abs(osugar)+"mg/dl less than the normal value of 100 mg/dl");
                        }
                        else
                        {
                            areaa.setText(areaa.getText()+" and it is "+Math.abs(osugar)+"mg/dl more than the normal value of 100 mg/dl");
                        }
		}
		else
		{
			areaa.setText(areaa.getText()+" Sugar level has increased by "+Math.abs(dsug)+"mg/dl");
                        if(osugar>0)
                        {
                          areaa.setText(areaa.getText()+" and it is "+Math.abs(osugar)+"mg/dl less than the normal value of 100 mg/dl");
                        }
                        else
                        {
                            areaa.setText(areaa.getText()+" and it is "+Math.abs(osugar)+"mg/dl more than the normal value of 100 mg/dl");
                        }
		}
		if(dchol>0)
		{
			areaa.setText(areaa.getText()+"\nCholestrol level has decreased by "+Math.abs(dchol)+"mg/dl");
                        if(ochol>0)
                        {
                          areaa.setText(areaa.getText()+" and it is "+Math.abs(ochol)+"mg/dl less than the normal value of 200 mg/dl");
                        }
                        else
                        {
                            areaa.setText(areaa.getText()+" and it is "+Math.abs(ochol)+"mg/dl more than the normal value of 200 mg/dl");
                        }
		}
		else
		{
			areaa.setText(areaa.getText()+"\nCholestrol level has increased by "+Math.abs(dchol)+"mg/dl");
                         if(ochol>0)
                        {
                          areaa.setText(areaa.getText()+" and it is "+Math.abs(ochol)+"mg/dl less than the normal value of 200 mg/dl");
                        }
                        else
                        {
                            areaa.setText(areaa.getText()+" and it is "+Math.abs(ochol)+"mg/dl more than the normal value of 200 mg/dl");
                        }
		}
		if(dwbc>0)
		{
			areaa.setText(areaa.getText()+"\nWBC count has decreased by "+Math.abs(dwbc)+"per cubic cm");
                         if(ochol>0)
                        {
                          areaa.setText(areaa.getText()+" and it is "+Math.abs(owbc)+"mg/dl less than the normal value of 7550 per cubic cm");
                        }
                        else
                        {
                            areaa.setText(areaa.getText()+" and it is "+Math.abs(owbc)+"mg/dl more than the normal value of 7550 per cubic cm");
                        }
		}
		else
		{
			areaa.setText(areaa.getText()+"\nWBC count has increased by "+Math.abs(dwbc)+"cubic cm");
                         if(ochol>0)
                        {
                          areaa.setText(areaa.getText()+" and it is "+Math.abs(owbc)+"mg/dl less than the normal value of 7550 per cubic cm");
                        }
                        else
                        {
                            areaa.setText(areaa.getText()+" and it is "+Math.abs(owbc)+"mg/dl more than the normal value of 7550 per cubic cm");
                        }

		}
		if(drbc>0)
		{
			areaa.setText(areaa.getText()+"\nRBC count has decreased by "+Math.abs(drbc)+"mcL");
                         if(ochol>0)
                        {
                          areaa.setText(areaa.getText()+" and it is "+Math.abs(orbc)+"mg/dl less than the normal value of 5.4 mcL");
                        }
                        else
                        {
                            areaa.setText(areaa.getText()+" and it is "+Math.abs(orbc)+"mg/dl more than the normal value of 5.4 mcL");
                        }

		}
		else
		{
			areaa.setText(areaa.getText()+"\nRBC count has increased by "+Math.abs(drbc)+"mcL");
                         if(ochol>0)
                        {
                          areaa.setText(areaa.getText()+" and it is "+Math.abs(orbc)+"mg/dl less than the normal value of 5.4 mcL");
                        }
                        else
                        {
                            areaa.setText(areaa.getText()+" and it is "+Math.abs(orbc)+"mg/dl more than the normal value of 5.4 mcL");
                        }
		}
		if(dplatelets>0)
		{
			areaa.setText(areaa.getText()+"\nPlatelets count has decreased by "+Math.abs(dplatelets)+"per microlitre");
                         if(oplat>0)
                        {
                          areaa.setText(areaa.getText()+" and it is "+Math.abs(oplat)+"mg/dl less than the normal value of 300000 per microlitre");
                        }
                        else
                        {
                            areaa.setText(areaa.getText()+" and it is "+Math.abs(oplat)+"mg/dl more than the normal value of 300000 per microlitre");
                        }
		}
		else
		{
			areaa.setText(areaa.getText()+"\nPlatelets count has increased by "+Math.abs(dplatelets)+"per microlitre");
                        if(oplat>0)
                        {
                          areaa.setText(areaa.getText()+" and it is "+Math.abs(oplat)+"mg/dl less than the normal value of 300000 per microlitre");
                        }
                        else
                        {
                            areaa.setText(areaa.getText()+" and it is "+Math.abs(oplat)+"mg/dl more than the normal value of 300000 per microlitre");
                        }
		}
		
		 // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ccholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccholActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccholActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analysis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaa;
    private javax.swing.JTextField cchol;
    private javax.swing.JTextField cplatelets;
    private javax.swing.JTextField crbc;
    private javax.swing.JTextField csugar;
    private javax.swing.JTextField cwbc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lchol;
    private javax.swing.JTextField lplatelets;
    private javax.swing.JTextField lrbc;
    private javax.swing.JTextField lsugar;
    private javax.swing.JTextField lwbc;
    // End of variables declaration//GEN-END:variables
}
